products:
- name: ポケモン30周年 ピカチュウ1/1
  url: https://www.edion.com/detail.html?p_cd=00084797278
  site: edion
  enabled: true
- name: iPhone 17 ラベンダー
  url: https://www.biccamera.com/bc/item/14459235/
  site: biccamera
  enabled: true
- name: iPhone 17 ブラック
  url: https://www.biccamera.com/bc/item/14459232/
  site: biccamera
  enabled: true
- name: iPhone 17 ホワイト
  url: https://www.biccamera.com/bc/item/14459233/
  site: biccamera
  enabled: true
- name: iPhone 17 ミストブルー
  url: https://www.biccamera.com/bc/item/14459234/
  site: biccamera
  enabled: true
- name: iPhone 17 セージ
  url: https://www.biccamera.com/bc/item/14459236/
  site: biccamera
  enabled: true
- name: テスト追加商品
  url: https://www.yodobashi.com/product/100000001007281670/
  site: yodobashi
  enabled: true
